FROM node:16 AS builder

WORKDIR /app

COPY package*.json ./

RUN ["npm", "install"]

COPY ./ ./

ARG _FIREBASE_API_KEY
ENV FIREBASE_API_KEY ${_FIREBASE_API_KEY}
ARG _FIREBASE_AUTH_DOMAIN
ENV FIREBASE_AUTH_DOMAIN ${_FIREBASE_AUTH_DOMAIN}
ARG _FIREBASE_DATABASE_URL
ENV FIREBASE_DATABASE_URL ${_FIREBASE_DATABASE_URL}
ARG _FIREBASE_PROJECT_ID
ENV FIREBASE_PROJECT_ID ${_FIREBASE_PROJECT_ID}
ARG _FIREBASE_STORAGE_BUCKET
ENV FIREBASE_STORAGE_BUCKET ${_FIREBASE_STORAGE_BUCKET}
ARG _FIREBASE_MESSAGING_SENDER_ID
ENV FIREBASE_MESSAGING_SENDER_ID ${_FIREBASE_MESSAGING_SENDER_ID}
ARG _FIREBASE_APP_ID
ENV FIREBASE_APP_ID ${_FIREBASE_APP_ID}
ARG _FIREBASE_MESUREMENT_ID
ENV FIREBASE_MESUREMENT_ID ${_FIREBASE_MESUREMENT_ID}

RUN ["npm", "run", "build"]

FROM nginx:alpine as server

COPY --from=builder /app/dist /usr/share/nginx/html

ENV PORT 8080
ENV HOST 0.0.0.0
EXPOSE 8080
COPY nginx.conf /etc/nginx/conf.d/configfile.template
CMD sh -c "envsubst '\$PORT' < /etc/nginx/conf.d/configfile.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
